// Localisation : les chaînes du code sont en anglais (fallback naturel),
// la table `fr` fournit la traduction. "auto" = langue du système.
// Certains libellés sensibles aux collisions (états logiques) utilisent des
// clés préfixées ("state.charging") traduites dans les deux tables.
import Foundation

func resolveLanguage(_ setting: String?) -> String {
    if setting == "fr" || setting == "en" { return setting ?? "en" }
    return (Locale.preferredLanguages.first ?? "en").lowercased().hasPrefix("fr")
        ? "fr" : "en"
}

enum L10n {
    static func text(_ key: String, lang: String) -> String {
        (lang == "fr" ? fr[key] : en[key]) ?? key
    }

    // Clés préfixées → libellé anglais
    static let en: [String: String] = [
        "state.charging": "charging",
        "state.discharging": "on battery",
        "state.plugged": "plugged in",
        "state.idle": "idle",
    ]

    static let fr: [String: String] = [
        // États
        "state.charging": "en charge",
        "state.discharging": "sur batterie",
        "state.plugged": "sur secteur",
        "state.idle": "au repos",

        // Panneau
        "Settings": "Réglages",
        "Time remaining": "Autonomie restante",
        "Full charge in": "Charge complète dans",
        "Mac on EcoFlow": "Mac sur l'EcoFlow",
        "State": "État",
        "Raw level": "Niveau réel",
        "window": "fenêtre",
        "Power flow": "Flux",
        "Input": "Entrée",
        "AC output": "Sortie AC",
        "USB-C output": "Sortie USB-C",
        "Mac CPU (internal)": "CPU du Mac (interne)",
        "Temperature": "Température",
        "Energy today": "Énergie aujourd'hui",
        "Automatic actions on the Mac": "Actions automatiques sur le Mac",
        "Hibernate: save session and shut down": "Hiberner : sauvegarder la session et éteindre",
        "Daemon log": "Journal du démon",
        "Quit EcoFlowBar": "Quitter EcoFlowBar",
        "Save the session and shut down the Mac?": "Sauvegarder la session et éteindre le Mac ?",
        "Apps, tabs and tmux will be restored on next startup.": "Apps, onglets et tmux seront restaurés au prochain démarrage.",
        "Cancel": "Annuler",
        "Shut down": "Éteindre",
        "Cut the Mac's power?": "Couper l'alimentation du Mac ?",
        "Cut power": "Couper",
        "Turn off AC output": "Couper la sortie AC",
        "Turn on AC output": "Activer la sortie AC",
        "full in": "pleine dans",
        "Daemon unreachable — see log": "Démon injoignable — voir le journal",
        "Bluetooth search…": "Recherche Bluetooth…",
        "EcoFlow out of range or off": "EcoFlow hors de portée ou éteinte",
        "Not configured": "Non configuré",
        "Waiting for daemon…": "En attente du démon…",
        "History": "Historique",
        "Collecting history…": "Historique en cours de collecte…",
        "Battery": "Batterie",
        "Load avg.": "Conso moy.",
        "CPU avg.": "CPU moy.",

        // Réglages
        "EcoFlow Settings": "Réglages EcoFlow",
        "General": "Général",
        "Account": "Compte",
        "Protection": "Protection",
        "Advanced": "Avancé",
        "Behavior": "Comportement",
        "Master switch: low power, shutdown, alerts": "Interrupteur maître : mode éco, extinction, alertes",
        "Power source changes, low battery, temperature": "Bascules secteur/batterie, batterie faible, température",
        "Launch at login": "Lancer au démarrage",
        "Menu bar": "Barre de menus",
        "Everything unchecked: the icon alone remains.": "Tout décoché : l'icône seule reste affichée.",
        "Battery icon": "Icône batterie",
        "Percentage": "Pourcentage",
        "Power draw": "Puissance débitée",
        "Language": "Langue",
        "Automatic (system)": "Automatique (système)",
        "EcoFlow account": "Compte EcoFlow",
        "Password sent only to EcoFlow, never stored.": "Mot de passe envoyé uniquement chez EcoFlow, jamais conservé.",
        "Password": "Mot de passe",
        "Sign in": "Se connecter",
        "Sign in…": "Se connecter…",
        "Change account…": "Changer de compte…",
        "Status": "Statut",
        "Connected": "Connecté",
        "Not signed in": "Non connecté",
        "Bluetooth pairing": "Appairage Bluetooth",
        "Current battery": "Batterie actuelle",
        "none": "aucune",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "Bluetooth refusé — Réglages → Confidentialité → Bluetooth",
        "Searching… is the battery on and nearby?": "Recherche… batterie allumée et à proximité ?",
        "✓ Current": "✓ Actuelle",
        "Select": "Choisir",
        "Searching": "Recherche en cours",
        "Stop": "Arrêter",
        "Change battery": "Changer de batterie",
        "The daemon releases Bluetooth during the search": "Le démon libère le Bluetooth pendant la recherche",
        "Search…": "Rechercher…",
        "Thresholds": "Seuils",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "En % effectif de la fenêtre utilisable. Le retour au mode normal reste au-dessus du seuil du mode éco (hystérésis).",
        "Notification": "Notification",
        "Low power": "Mode éco",
        "Shutdown": "Extinction",
        "Return to normal": "Retour au mode normal",
        "Options": "Options",
        "Automatic low power": "Mode éco automatique",
        "Throttles the Mac below the threshold, via pmset": "Bride le Mac sous le seuil, via pmset",
        "Low power as soon as on battery": "Mode éco dès la batterie",
        "Without waiting for the threshold, as soon as AC is lost": "Sans attendre le seuil, dès la perte du secteur",
        "Automatic shutdown": "Extinction automatique",
        "Pseudo-hibernation at critical level": "Pseudo-hibernation au niveau critique",
        "Only when the Mac is on the EcoFlow": "Seulement si le Mac est sur l'EcoFlow",
        "Detected via AC output watts": "Détection via les watts de la sortie AC",
        "Displayed % and time remaining are relative to the usable window.": "Le % et l'autonomie affichés sont rapportés à la fenêtre utilisable.",
        "Applied window": "Fenêtre appliquée",
        "Charge limit": "Limite de charge",
        "80-85% daily extends LFP cell lifespan.": "80-85 % au quotidien prolonge la durée de vie des cellules LFP.",
        "Manage the charge limit": "Piloter la limite de charge",
        "Charge up to": "Charger jusqu'à",
        "Discharge reserve": "Réserve de décharge",
        "A reserve avoids deep discharge and keeps an emergency margin.": "Une réserve évite la décharge profonde et garde une marge de secours.",
        "Manage the discharge limit": "Piloter la limite de décharge",
        "Minimum reserve": "Réserve minimale",
        "Measurement": "Mesure",
        "Refresh interval": "Rafraîchissement",
        "\"Mac plugged\" threshold": "Seuil « Mac branché »",
        "Shutdown warning delay": "Préavis d'extinction",
        "Maintenance": "Maintenance",
        "Configuration file": "Fichier de configuration",
        "Open": "Ouvrir",
        "Monitoring daemon": "Démon de surveillance",
        "Restart": "Relancer",
        "Danger zone": "Zone sensible",
        "Reset the app": "Réinitialiser l'application",
        "Clears account and pairing, replays the full setup": "Efface compte et appairage, rejoue la configuration complète",
        "Reset…": "Réinitialiser…",
        "Reset EcoFlowBar?": "Réinitialiser EcoFlowBar ?",
        "Reset and relaunch": "Réinitialiser et relancer",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "Le compte EcoFlow et l'appairage seront effacés, puis l'app relancera la configuration complète.",

        // Onboarding + intro
        "Hello.": "Bonjour.",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "Votre batterie EcoFlow, dans la barre des menus.\nAutonomie réelle, protection automatique du Mac, 100 % local en Bluetooth.",
        "Get started": "Commencer",
        "Your account.": "Votre compte.",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "Le Bluetooth EcoFlow exige l'identifiant du compte lié à la batterie. Le mot de passe part uniquement chez EcoFlow — jamais conservé.",
        "Account connected": "Compte connecté",
        "Continue": "Continuer",
        "Later": "Plus tard",
        "In range.": "À portée.",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "L'accès Bluetooth est refusé — autorisez EcoFlowBar dans les réglages de confidentialité.",
        "Open Privacy → Bluetooth": "Ouvrir Confidentialité → Bluetooth",
        "Turn on your battery and keep it nearby.": "Allumez votre batterie et gardez-la à proximité.",
        "Choose the battery to monitor.": "Choisissez la batterie à suivre.",
        "Your rules.": "Vos règles.",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "Ce qu'EcoFlowBar peut faire pour vous — tout reste modifiable à tout moment dans Réglages.",
        "Notifications (source changes, low battery)": "Notifications (bascules, batterie faible)",
        "Automatic actions on the Mac (low power…)": "Actions automatiques sur le Mac (mode éco…)",
        "Limit the charge range (battery health)": "Limiter la plage de charge (santé batterie)",
        "Min reserve": "Réserve min",
        "Max charge": "Charge max",
        "The Mac's keys.": "Les clés du Mac.",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "Pour activer le mode économie d'énergie, l'extinction propre et la mesure CPU, macOS demandera une fois votre mot de passe administrateur. Optionnel — l'affichage fonctionne sans.",
        "Permissions installed": "Autorisations installées",
        "Permissions not installed": "Autorisations non installées",
        "Install…": "Installer…",
        "Skip": "Passer",
        "All set.": "C'est prêt.",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "L'indicateur vit maintenant dans votre barre des menus, mis à jour en Bluetooth, sans Internet. Tous les ajustements sont dans Réglages.",
        "Finish": "Terminer",
        "Back": "Précédent",
        "Let's set up your EcoFlow battery.": "Configurons votre batterie EcoFlow.",
        "click to continue": "cliquez pour continuer",
        "credentials rejected": "identifiants refusés",
        "Unexpected server response": "Réponse inattendue du serveur",
        "Network error": "Erreur réseau",
    ]
}
