// Localisation : les chaînes du code sont en anglais (fallback naturel),
// la table `fr` fournit la traduction. "auto" = langue du système.
// Certains libellés sensibles aux collisions (états logiques) utilisent des
// clés préfixées ("state.charging") traduites dans les deux tables.
import Foundation

let supportedLanguages = ["en", "fr", "de", "es", "ja", "zh"]

func resolveLanguage(_ setting: String?) -> String {
    if let setting, supportedLanguages.contains(setting) { return setting }
    for preferred in Locale.preferredLanguages {
        let code = preferred.lowercased()
        if let match = supportedLanguages.first(where: { code.hasPrefix($0) }) {
            return match
        }
    }
    return "en"
}

enum L10n {
    // (code, nom natif) pour les sélecteurs de langue
    static let choices: [(String, String)] = [
        ("auto", ""), ("en", "English"), ("fr", "Français"),
        ("de", "Deutsch"), ("es", "Español"), ("ja", "日本語"), ("zh", "中文"),
    ]

    static func text(_ key: String, lang: String) -> String {
        let table: [String: String]
        switch lang {
        case "fr": table = fr
        case "de": table = de
        case "es": table = es
        case "ja": table = ja
        case "zh": table = zh
        default: table = en
        }
        return table[key] ?? en[key] ?? key
    }

    // Clés préfixées → libellé anglais
    static let en: [String: String] = [
        "state.charging": "charging",
        "state.discharging": "on battery",
        "state.plugged": "plugged in",
        "state.idle": "idle",
    ]

    static let fr: [String: String] = [
        // États
        "state.charging": "en charge",
        "state.discharging": "sur batterie",
        "state.plugged": "sur secteur",
        "state.idle": "au repos",

        // Panneau
        "Settings": "Réglages",
        "Time remaining": "Autonomie restante",
        "Full charge in": "Charge complète dans",
        "Mac on EcoFlow": "Mac sur l'EcoFlow",
        "State": "État",
        "Raw level": "Niveau réel",
        "window": "fenêtre",
        "Power flow": "Flux",
        "Input": "Entrée",
        "AC output": "Sortie AC",
        "USB-C output": "Sortie USB-C",
        "Mac CPU (internal)": "CPU du Mac (interne)",
        "Temperature": "Température",
        "Energy today": "Énergie aujourd'hui",
        "Automatic actions on the Mac": "Actions automatiques sur le Mac",
        "Hibernate: save session and shut down": "Hiberner : sauvegarder la session et éteindre",
        "Daemon log": "Journal du démon",
        "Quit EcoFlowBar": "Quitter EcoFlowBar",
        "Save the session and shut down the Mac?": "Sauvegarder la session et éteindre le Mac ?",
        "Apps, tabs and tmux will be restored on next startup.": "Apps, onglets et tmux seront restaurés au prochain démarrage.",
        "Cancel": "Annuler",
        "Shut down": "Éteindre",
        "Cut the Mac's power?": "Couper l'alimentation du Mac ?",
        "Cut power": "Couper",
        "Turn off AC output": "Couper la sortie AC",
        "Turn on AC output": "Activer la sortie AC",
        "full in": "pleine dans",
        "Daemon unreachable — see log": "Démon injoignable — voir le journal",
        "Bluetooth search…": "Recherche Bluetooth…",
        "EcoFlow out of range or off": "EcoFlow hors de portée ou éteinte",
        "Not configured": "Non configuré",
        "Waiting for daemon…": "En attente du démon…",
        "History": "Historique",
        "Collecting history…": "Historique en cours de collecte…",
        "Battery": "Batterie",
        "Load avg.": "Conso moy.",
        "CPU avg.": "CPU moy.",

        // Réglages
        "EcoFlow Settings": "Réglages EcoFlow",
        "General": "Général",
        "Account": "Compte",
        "Protection": "Protection",
        "Advanced": "Avancé",
        "Behavior": "Comportement",
        "Master switch: low power, shutdown, alerts": "Interrupteur maître : mode éco, extinction, alertes",
        "Power source changes, low battery, temperature": "Bascules secteur/batterie, batterie faible, température",
        "Launch at login": "Lancer au démarrage",
        "Menu bar": "Barre de menus",
        "Everything unchecked: the icon alone remains.": "Tout décoché : l'icône seule reste affichée.",
        "Battery icon": "Icône batterie",
        "Percentage": "Pourcentage",
        "Power draw": "Puissance débitée",
        "Language": "Langue",
        "Automatic (system)": "Automatique (système)",
        "EcoFlow account": "Compte EcoFlow",
        "Password sent only to EcoFlow, never stored.": "Mot de passe envoyé uniquement chez EcoFlow, jamais conservé.",
        "Password": "Mot de passe",
        "Sign in": "Se connecter",
        "Sign in…": "Se connecter…",
        "Change account…": "Changer de compte…",
        "Status": "Statut",
        "Connected": "Connecté",
        "Not signed in": "Non connecté",
        "Bluetooth pairing": "Appairage Bluetooth",
        "Current battery": "Batterie actuelle",
        "none": "aucune",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "Bluetooth refusé — Réglages → Confidentialité → Bluetooth",
        "Searching… is the battery on and nearby?": "Recherche… batterie allumée et à proximité ?",
        "✓ Current": "✓ Actuelle",
        "Select": "Choisir",
        "Searching": "Recherche en cours",
        "Stop": "Arrêter",
        "Change battery": "Changer de batterie",
        "The daemon releases Bluetooth during the search": "Le démon libère le Bluetooth pendant la recherche",
        "Search…": "Rechercher…",
        "Thresholds": "Seuils",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "En % effectif de la fenêtre utilisable. Le retour au mode normal reste au-dessus du seuil du mode éco (hystérésis).",
        "Notification": "Notification",
        "Low power": "Mode éco",
        "Shutdown": "Extinction",
        "Return to normal": "Retour au mode normal",
        "Options": "Options",
        "Automatic low power": "Mode éco automatique",
        "Throttles the Mac below the threshold, via pmset": "Bride le Mac sous le seuil, via pmset",
        "Low power as soon as on battery": "Mode éco dès la batterie",
        "Without waiting for the threshold, as soon as AC is lost": "Sans attendre le seuil, dès la perte du secteur",
        "Automatic shutdown": "Extinction automatique",
        "Pseudo-hibernation at critical level": "Pseudo-hibernation au niveau critique",
        "Only when the Mac is on the EcoFlow": "Seulement si le Mac est sur l'EcoFlow",
        "Detected via AC output watts": "Détection via les watts de la sortie AC",
        "Displayed % and time remaining are relative to the usable window.": "Le % et l'autonomie affichés sont rapportés à la fenêtre utilisable.",
        "Applied window": "Fenêtre appliquée",
        "Charge limit": "Limite de charge",
        "80-85% daily extends LFP cell lifespan.": "80-85 % au quotidien prolonge la durée de vie des cellules LFP.",
        "Manage the charge limit": "Piloter la limite de charge",
        "Charge up to": "Charger jusqu'à",
        "Discharge reserve": "Réserve de décharge",
        "A reserve avoids deep discharge and keeps an emergency margin.": "Une réserve évite la décharge profonde et garde une marge de secours.",
        "Manage the discharge limit": "Piloter la limite de décharge",
        "Minimum reserve": "Réserve minimale",
        "Measurement": "Mesure",
        "Refresh interval": "Rafraîchissement",
        "\"Mac plugged\" threshold": "Seuil « Mac branché »",
        "Shutdown warning delay": "Préavis d'extinction",
        "Maintenance": "Maintenance",
        "Configuration file": "Fichier de configuration",
        "Open": "Ouvrir",
        "Monitoring daemon": "Démon de surveillance",
        "Restart": "Relancer",
        "Danger zone": "Zone sensible",
        "Reset the app": "Réinitialiser l'application",
        "Clears account and pairing, replays the full setup": "Efface compte et appairage, rejoue la configuration complète",
        "Reset…": "Réinitialiser…",
        "Reset EcoFlowBar?": "Réinitialiser EcoFlowBar ?",
        "Reset and relaunch": "Réinitialiser et relancer",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "Le compte EcoFlow et l'appairage seront effacés, puis l'app relancera la configuration complète.",

        // Onboarding + intro
        "Hello.": "Bonjour.",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "Votre batterie EcoFlow, dans la barre des menus.\nAutonomie réelle, protection automatique du Mac, 100 % local en Bluetooth.",
        "Get started": "Commencer",
        "Your account.": "Votre compte.",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "Le Bluetooth EcoFlow exige l'identifiant du compte lié à la batterie. Le mot de passe part uniquement chez EcoFlow — jamais conservé.",
        "Account connected": "Compte connecté",
        "Continue": "Continuer",
        "Later": "Plus tard",
        "In range.": "À portée.",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "L'accès Bluetooth est refusé — autorisez EcoFlowBar dans les réglages de confidentialité.",
        "Open Privacy → Bluetooth": "Ouvrir Confidentialité → Bluetooth",
        "Turn on your battery and keep it nearby.": "Allumez votre batterie et gardez-la à proximité.",
        "Choose the battery to monitor.": "Choisissez la batterie à suivre.",
        "Your rules.": "Vos règles.",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "Ce qu'EcoFlowBar peut faire pour vous — tout reste modifiable à tout moment dans Réglages.",
        "Notifications (source changes, low battery)": "Notifications (bascules, batterie faible)",
        "Automatic actions on the Mac (low power…)": "Actions automatiques sur le Mac (mode éco…)",
        "Limit the charge range (battery health)": "Limiter la plage de charge (santé batterie)",
        "Min reserve": "Réserve min",
        "Max charge": "Charge max",
        "The Mac's keys.": "Les clés du Mac.",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "Pour activer le mode économie d'énergie, l'extinction propre et la mesure CPU, macOS demandera une fois votre mot de passe administrateur. Optionnel — l'affichage fonctionne sans.",
        "Permissions installed": "Autorisations installées",
        "Permissions not installed": "Autorisations non installées",
        "Install…": "Installer…",
        "Skip": "Passer",
        "All set.": "C'est prêt.",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "L'indicateur vit maintenant dans votre barre des menus, mis à jour en Bluetooth, sans Internet. Tous les ajustements sont dans Réglages.",
        "Finish": "Terminer",
        "Back": "Précédent",
        "Let's set up your EcoFlow battery.": "Configurons votre batterie EcoFlow.",
        "click to continue": "cliquez pour continuer",
        "credentials rejected": "identifiants refusés",
        "Unexpected server response": "Réponse inattendue du serveur",
        "Network error": "Erreur réseau",
    ]

    static let es: [String: String] = [
        "state.charging": "cargando",
        "state.discharging": "con batería",
        "state.plugged": "enchufado",
        "state.idle": "en reposo",
        "Settings": "Ajustes",
        "Time remaining": "Autonomía restante",
        "Full charge in": "Carga completa en",
        "Mac on EcoFlow": "Mac con la EcoFlow",
        "State": "Estado",
        "Raw level": "Nivel real",
        "window": "ventana",
        "Power flow": "Flujo de energía",
        "Input": "Entrada",
        "AC output": "Salida CA",
        "USB-C output": "Salida USB-C",
        "Mac CPU (internal)": "CPU del Mac (interna)",
        "Temperature": "Temperatura",
        "Energy today": "Energía hoy",
        "Automatic actions on the Mac": "Acciones automáticas en el Mac",
        "Hibernate: save session and shut down": "Hibernar: guardar la sesión y apagar",
        "Daemon log": "Registro del demonio",
        "Quit EcoFlowBar": "Salir de EcoFlowBar",
        "Save the session and shut down the Mac?": "¿Guardar la sesión y apagar el Mac?",
        "Apps, tabs and tmux will be restored on next startup.": "Apps, pestañas y tmux se restaurarán en el próximo inicio.",
        "Cancel": "Cancelar",
        "Shut down": "Apagar",
        "Cut the Mac's power?": "¿Cortar la alimentación del Mac?",
        "Cut power": "Cortar",
        "Turn off AC output": "Apagar la salida CA",
        "Turn on AC output": "Encender la salida CA",
        "full in": "completa en",
        "Daemon unreachable — see log": "Demonio inalcanzable — ver registro",
        "Bluetooth search…": "Buscando por Bluetooth…",
        "EcoFlow out of range or off": "EcoFlow fuera de alcance o apagada",
        "Not configured": "Sin configurar",
        "Waiting for daemon…": "Esperando al demonio…",
        "History": "Historial",
        "Collecting history…": "Recopilando historial…",
        "Battery": "Batería",
        "Load avg.": "Consumo med.",
        "CPU avg.": "CPU med.",
        "EcoFlow Settings": "Ajustes de EcoFlow",
        "General": "General",
        "Account": "Cuenta",
        "Protection": "Protección",
        "Advanced": "Avanzado",
        "Behavior": "Comportamiento",
        "Master switch: low power, shutdown, alerts": "Interruptor maestro: ahorro, apagado, alertas",
        "Power source changes, low battery, temperature": "Cambios de fuente, batería baja, temperatura",
        "Launch at login": "Abrir al iniciar sesión",
        "Menu bar": "Barra de menús",
        "Everything unchecked: the icon alone remains.": "Todo desmarcado: solo queda el icono.",
        "Battery icon": "Icono de batería",
        "Percentage": "Porcentaje",
        "Power draw": "Potencia consumida",
        "Language": "Idioma",
        "Automatic (system)": "Automático (sistema)",
        "EcoFlow account": "Cuenta EcoFlow",
        "Password sent only to EcoFlow, never stored.": "La contraseña se envía solo a EcoFlow, nunca se guarda.",
        "Password": "Contraseña",
        "Sign in": "Iniciar sesión",
        "Sign in…": "Iniciar sesión…",
        "Change account…": "Cambiar de cuenta…",
        "Status": "Estado",
        "Connected": "Conectado",
        "Not signed in": "Sin iniciar sesión",
        "Bluetooth pairing": "Emparejamiento Bluetooth",
        "Current battery": "Batería actual",
        "none": "ninguna",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "Bluetooth denegado — Ajustes → Privacidad → Bluetooth",
        "Searching… is the battery on and nearby?": "Buscando… ¿la batería está encendida y cerca?",
        "✓ Current": "✓ Actual",
        "Select": "Elegir",
        "Searching": "Buscando",
        "Stop": "Detener",
        "Change battery": "Cambiar de batería",
        "The daemon releases Bluetooth during the search": "El demonio libera el Bluetooth durante la búsqueda",
        "Search…": "Buscar…",
        "Thresholds": "Umbrales",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "En % efectivo de la ventana utilizable. El retorno al modo normal se mantiene por encima del umbral de ahorro (histéresis).",
        "Notification": "Notificación",
        "Low power": "Ahorro de energía",
        "Shutdown": "Apagado",
        "Return to normal": "Volver al modo normal",
        "Options": "Opciones",
        "Automatic low power": "Ahorro de energía automático",
        "Throttles the Mac below the threshold, via pmset": "Limita el Mac bajo el umbral, mediante pmset",
        "Low power as soon as on battery": "Ahorro en cuanto pasa a batería",
        "Without waiting for the threshold, as soon as AC is lost": "Sin esperar al umbral, en cuanto se pierde la CA",
        "Automatic shutdown": "Apagado automático",
        "Pseudo-hibernation at critical level": "Pseudo-hibernación en nivel crítico",
        "Only when the Mac is on the EcoFlow": "Solo si el Mac está en la EcoFlow",
        "Detected via AC output watts": "Detectado por los vatios de salida CA",
        "Displayed % and time remaining are relative to the usable window.": "El % y la autonomía mostrados se refieren a la ventana utilizable.",
        "Applied window": "Ventana aplicada",
        "Charge limit": "Límite de carga",
        "80-85% daily extends LFP cell lifespan.": "80-85 % a diario alarga la vida de las celdas LFP.",
        "Manage the charge limit": "Controlar el límite de carga",
        "Charge up to": "Cargar hasta",
        "Discharge reserve": "Reserva de descarga",
        "A reserve avoids deep discharge and keeps an emergency margin.": "Una reserva evita la descarga profunda y guarda un margen de emergencia.",
        "Manage the discharge limit": "Controlar el límite de descarga",
        "Minimum reserve": "Reserva mínima",
        "Measurement": "Medición",
        "Refresh interval": "Intervalo de actualización",
        "\"Mac plugged\" threshold": "Umbral «Mac conectado»",
        "Shutdown warning delay": "Aviso previo al apagado",
        "Maintenance": "Mantenimiento",
        "Configuration file": "Archivo de configuración",
        "Open": "Abrir",
        "Monitoring daemon": "Demonio de monitorización",
        "Restart": "Reiniciar",
        "Danger zone": "Zona sensible",
        "Reset the app": "Restablecer la app",
        "Clears account and pairing, replays the full setup": "Borra cuenta y emparejamiento, repite la configuración completa",
        "Reset…": "Restablecer…",
        "Reset EcoFlowBar?": "¿Restablecer EcoFlowBar?",
        "Reset and relaunch": "Restablecer y reiniciar",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "Se borrarán la cuenta EcoFlow y el emparejamiento, y la app repetirá la configuración completa.",
        "Hello.": "Hola.",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "Tu batería EcoFlow, en la barra de menús.\nAutonomía real, protección automática del Mac, 100 % local por Bluetooth.",
        "Get started": "Empezar",
        "Your account.": "Tu cuenta.",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "El Bluetooth de EcoFlow necesita el ID de la cuenta vinculada a la batería. La contraseña va solo a EcoFlow, nunca se guarda.",
        "Account connected": "Cuenta conectada",
        "Continue": "Continuar",
        "Later": "Más tarde",
        "In range.": "Al alcance.",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "Acceso Bluetooth denegado — permite EcoFlowBar en los ajustes de privacidad.",
        "Open Privacy → Bluetooth": "Abrir Privacidad → Bluetooth",
        "Turn on your battery and keep it nearby.": "Enciende la batería y mantenla cerca.",
        "Choose the battery to monitor.": "Elige la batería a monitorizar.",
        "Your rules.": "Tus reglas.",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "Lo que EcoFlowBar puede hacer por ti — todo se puede ajustar luego en Ajustes.",
        "Notifications (source changes, low battery)": "Notificaciones (cambios de fuente, batería baja)",
        "Automatic actions on the Mac (low power…)": "Acciones automáticas en el Mac (ahorro…)",
        "Limit the charge range (battery health)": "Limitar el rango de carga (salud de la batería)",
        "Min reserve": "Reserva mín.",
        "Max charge": "Carga máx.",
        "The Mac's keys.": "Las llaves del Mac.",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "Para el modo de ahorro, el apagado limpio y la medición de CPU, macOS pedirá una vez tu contraseña de administrador. Opcional — la visualización funciona sin ella.",
        "Permissions installed": "Permisos instalados",
        "Permissions not installed": "Permisos no instalados",
        "Install…": "Instalar…",
        "Skip": "Omitir",
        "All set.": "Todo listo.",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "El indicador ya vive en tu barra de menús, actualizado por Bluetooth, sin necesidad de Internet. Todos los ajustes están en Ajustes.",
        "Finish": "Finalizar",
        "Back": "Atrás",
        "Let's set up your EcoFlow battery.": "Vamos a configurar tu batería EcoFlow.",
        "click to continue": "haz clic para continuar",
        "credentials rejected": "credenciales rechazadas",
        "Unexpected server response": "Respuesta inesperada del servidor",
        "Network error": "Error de red",
    ]

    static let de: [String: String] = [
        "state.charging": "lädt",
        "state.discharging": "auf Akku",
        "state.plugged": "am Netz",
        "state.idle": "im Leerlauf",
        "Settings": "Einstellungen",
        "Time remaining": "Verbleibende Laufzeit",
        "Full charge in": "Voll geladen in",
        "Mac on EcoFlow": "Mac an der EcoFlow",
        "State": "Status",
        "Raw level": "Tatsächlicher Stand",
        "window": "Fenster",
        "Power flow": "Leistungsfluss",
        "Input": "Eingang",
        "AC output": "AC-Ausgang",
        "USB-C output": "USB-C-Ausgang",
        "Mac CPU (internal)": "Mac-CPU (intern)",
        "Temperature": "Temperatur",
        "Energy today": "Energie heute",
        "Automatic actions on the Mac": "Automatische Aktionen auf dem Mac",
        "Hibernate: save session and shut down": "Ruhezustand: Sitzung sichern und herunterfahren",
        "Daemon log": "Daemon-Protokoll",
        "Quit EcoFlowBar": "EcoFlowBar beenden",
        "Save the session and shut down the Mac?": "Sitzung sichern und den Mac herunterfahren?",
        "Apps, tabs and tmux will be restored on next startup.": "Apps, Tabs und tmux werden beim nächsten Start wiederhergestellt.",
        "Cancel": "Abbrechen",
        "Shut down": "Herunterfahren",
        "Cut the Mac's power?": "Stromversorgung des Mac trennen?",
        "Cut power": "Trennen",
        "Turn off AC output": "AC-Ausgang ausschalten",
        "Turn on AC output": "AC-Ausgang einschalten",
        "full in": "voll in",
        "Daemon unreachable — see log": "Daemon nicht erreichbar — siehe Protokoll",
        "Bluetooth search…": "Bluetooth-Suche…",
        "EcoFlow out of range or off": "EcoFlow außer Reichweite oder aus",
        "Not configured": "Nicht konfiguriert",
        "Waiting for daemon…": "Warte auf den Daemon…",
        "History": "Verlauf",
        "Collecting history…": "Verlauf wird gesammelt…",
        "Battery": "Akku",
        "Load avg.": "Verbrauch Ø",
        "CPU avg.": "CPU Ø",
        "EcoFlow Settings": "EcoFlow-Einstellungen",
        "General": "Allgemein",
        "Account": "Konto",
        "Protection": "Schutz",
        "Advanced": "Erweitert",
        "Behavior": "Verhalten",
        "Master switch: low power, shutdown, alerts": "Hauptschalter: Stromsparmodus, Herunterfahren, Hinweise",
        "Power source changes, low battery, temperature": "Quellenwechsel, niedriger Akkustand, Temperatur",
        "Launch at login": "Beim Anmelden starten",
        "Menu bar": "Menüleiste",
        "Everything unchecked: the icon alone remains.": "Alles abgewählt: nur das Symbol bleibt sichtbar.",
        "Battery icon": "Akku-Symbol",
        "Percentage": "Prozentwert",
        "Power draw": "Leistungsaufnahme",
        "Language": "Sprache",
        "Automatic (system)": "Automatisch (System)",
        "EcoFlow account": "EcoFlow-Konto",
        "Password sent only to EcoFlow, never stored.": "Passwort wird nur an EcoFlow gesendet, nie gespeichert.",
        "Password": "Passwort",
        "Sign in": "Anmelden",
        "Sign in…": "Anmelden…",
        "Change account…": "Konto wechseln…",
        "Status": "Status",
        "Connected": "Angemeldet",
        "Not signed in": "Nicht angemeldet",
        "Bluetooth pairing": "Bluetooth-Kopplung",
        "Current battery": "Aktueller Akku",
        "none": "keiner",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "Bluetooth verweigert — Einstellungen → Datenschutz → Bluetooth",
        "Searching… is the battery on and nearby?": "Suche… ist der Akku an und in der Nähe?",
        "✓ Current": "✓ Aktuell",
        "Select": "Auswählen",
        "Searching": "Suche läuft",
        "Stop": "Stoppen",
        "Change battery": "Akku wechseln",
        "The daemon releases Bluetooth during the search": "Der Daemon gibt Bluetooth während der Suche frei",
        "Search…": "Suchen…",
        "Thresholds": "Schwellenwerte",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "In effektiven % des nutzbaren Fensters. Die Rückkehr zum Normalmodus bleibt über der Stromspar-Schwelle (Hysterese).",
        "Notification": "Benachrichtigung",
        "Low power": "Stromsparmodus",
        "Shutdown": "Herunterfahren",
        "Return to normal": "Zurück zum Normalmodus",
        "Options": "Optionen",
        "Automatic low power": "Automatischer Stromsparmodus",
        "Throttles the Mac below the threshold, via pmset": "Drosselt den Mac unterhalb der Schwelle, via pmset",
        "Low power as soon as on battery": "Stromsparmodus sofort im Akkubetrieb",
        "Without waiting for the threshold, as soon as AC is lost": "Ohne Schwelle, sobald das Netz wegfällt",
        "Automatic shutdown": "Automatisches Herunterfahren",
        "Pseudo-hibernation at critical level": "Pseudo-Ruhezustand bei kritischem Stand",
        "Only when the Mac is on the EcoFlow": "Nur wenn der Mac an der EcoFlow hängt",
        "Detected via AC output watts": "Erkannt über die Watt am AC-Ausgang",
        "Displayed % and time remaining are relative to the usable window.": "Angezeigte % und Laufzeit beziehen sich auf das nutzbare Fenster.",
        "Applied window": "Angewendetes Fenster",
        "Charge limit": "Ladelimit",
        "80-85% daily extends LFP cell lifespan.": "80-85 % im Alltag verlängert die Lebensdauer der LFP-Zellen.",
        "Manage the charge limit": "Ladelimit verwalten",
        "Charge up to": "Laden bis",
        "Discharge reserve": "Entladereserve",
        "A reserve avoids deep discharge and keeps an emergency margin.": "Eine Reserve verhindert Tiefentladung und bewahrt eine Notfallmarge.",
        "Manage the discharge limit": "Entladelimit verwalten",
        "Minimum reserve": "Mindestreserve",
        "Measurement": "Messung",
        "Refresh interval": "Aktualisierungsintervall",
        "\"Mac plugged\" threshold": "Schwelle „Mac angeschlossen“",
        "Shutdown warning delay": "Vorwarnzeit vor dem Herunterfahren",
        "Maintenance": "Wartung",
        "Configuration file": "Konfigurationsdatei",
        "Open": "Öffnen",
        "Monitoring daemon": "Überwachungs-Daemon",
        "Restart": "Neu starten",
        "Danger zone": "Gefahrenzone",
        "Reset the app": "App zurücksetzen",
        "Clears account and pairing, replays the full setup": "Löscht Konto und Kopplung, startet die Einrichtung neu",
        "Reset…": "Zurücksetzen…",
        "Reset EcoFlowBar?": "EcoFlowBar zurücksetzen?",
        "Reset and relaunch": "Zurücksetzen und neu starten",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "EcoFlow-Konto und Kopplung werden gelöscht, danach startet die App die komplette Einrichtung neu.",
        "Hello.": "Hallo.",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "Deine EcoFlow, in der Menüleiste.\nEchte Restlaufzeit, automatischer Mac-Schutz, 100 % lokal über Bluetooth.",
        "Get started": "Los geht's",
        "Your account.": "Dein Konto.",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "EcoFlows Bluetooth benötigt die ID des mit dem Akku verknüpften Kontos. Das Passwort geht nur an EcoFlow — nie gespeichert.",
        "Account connected": "Konto verbunden",
        "Continue": "Weiter",
        "Later": "Später",
        "In range.": "In Reichweite.",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "Bluetooth-Zugriff verweigert — erlaube EcoFlowBar in den Datenschutz-Einstellungen.",
        "Open Privacy → Bluetooth": "Datenschutz → Bluetooth öffnen",
        "Turn on your battery and keep it nearby.": "Schalte deinen Akku ein und halte ihn in der Nähe.",
        "Choose the battery to monitor.": "Wähle den zu überwachenden Akku.",
        "Your rules.": "Deine Regeln.",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "Was EcoFlowBar für dich tun darf — alles bleibt in den Einstellungen anpassbar.",
        "Notifications (source changes, low battery)": "Benachrichtigungen (Quellenwechsel, niedriger Stand)",
        "Automatic actions on the Mac (low power…)": "Automatische Aktionen auf dem Mac (Stromsparmodus…)",
        "Limit the charge range (battery health)": "Ladebereich begrenzen (Akkugesundheit)",
        "Min reserve": "Min. Reserve",
        "Max charge": "Max. Ladung",
        "The Mac's keys.": "Die Schlüssel zum Mac.",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "Für Stromsparmodus, sauberes Herunterfahren und CPU-Messung fragt macOS einmal nach deinem Administrator-Passwort. Optional — die Anzeige funktioniert auch ohne.",
        "Permissions installed": "Berechtigungen installiert",
        "Permissions not installed": "Berechtigungen nicht installiert",
        "Install…": "Installieren…",
        "Skip": "Überspringen",
        "All set.": "Fertig.",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "Die Anzeige lebt jetzt in deiner Menüleiste, aktualisiert über Bluetooth, ganz ohne Internet. Alle Anpassungen findest du in den Einstellungen.",
        "Finish": "Fertigstellen",
        "Back": "Zurück",
        "Let's set up your EcoFlow battery.": "Richten wir deine EcoFlow ein.",
        "click to continue": "zum Fortfahren klicken",
        "credentials rejected": "Zugangsdaten abgelehnt",
        "Unexpected server response": "Unerwartete Serverantwort",
        "Network error": "Netzwerkfehler",
    ]

    static let ja: [String: String] = [
        "state.charging": "充電中",
        "state.discharging": "バッテリー駆動",
        "state.plugged": "電源接続中",
        "state.idle": "待機中",
        "Settings": "設定",
        "Time remaining": "残り時間",
        "Full charge in": "満充電まで",
        "Mac on EcoFlow": "MacはEcoFlowに接続",
        "State": "状態",
        "Raw level": "実残量",
        "window": "範囲",
        "Power flow": "電力フロー",
        "Input": "入力",
        "AC output": "AC出力",
        "USB-C output": "USB-C出力",
        "Mac CPU (internal)": "MacのCPU（内部）",
        "Temperature": "温度",
        "Energy today": "本日の電力量",
        "Automatic actions on the Mac": "Macの自動アクション",
        "Hibernate: save session and shut down": "休止：セッションを保存して終了",
        "Daemon log": "デーモンのログ",
        "Quit EcoFlowBar": "EcoFlowBarを終了",
        "Save the session and shut down the Mac?": "セッションを保存してMacをシステム終了しますか？",
        "Apps, tabs and tmux will be restored on next startup.": "アプリ、タブ、tmuxは次回起動時に復元されます。",
        "Cancel": "キャンセル",
        "Shut down": "システム終了",
        "Cut the Mac's power?": "Macへの給電を停止しますか？",
        "Cut power": "停止",
        "Turn off AC output": "AC出力をオフ",
        "Turn on AC output": "AC出力をオン",
        "full in": "満充電まで",
        "Daemon unreachable — see log": "デーモンに接続不可 — ログを確認",
        "Bluetooth search…": "Bluetooth検索中…",
        "EcoFlow out of range or off": "EcoFlowが圏外または電源オフ",
        "Not configured": "未設定",
        "Waiting for daemon…": "デーモンを待機中…",
        "History": "履歴",
        "Collecting history…": "履歴を収集中…",
        "Battery": "バッテリー",
        "Load avg.": "平均消費",
        "CPU avg.": "CPU平均",
        "EcoFlow Settings": "EcoFlow設定",
        "General": "一般",
        "Account": "アカウント",
        "Protection": "保護",
        "Advanced": "詳細",
        "Behavior": "動作",
        "Master switch: low power, shutdown, alerts": "マスタースイッチ：低電力モード・終了・通知",
        "Power source changes, low battery, temperature": "電源切替・バッテリー残量低下・温度",
        "Launch at login": "ログイン時に起動",
        "Menu bar": "メニューバー",
        "Everything unchecked: the icon alone remains.": "すべてオフの場合、アイコンのみ表示されます。",
        "Battery icon": "バッテリーアイコン",
        "Percentage": "パーセント",
        "Power draw": "消費電力",
        "Language": "言語",
        "Automatic (system)": "自動（システム）",
        "EcoFlow account": "EcoFlowアカウント",
        "Password sent only to EcoFlow, never stored.": "パスワードはEcoFlowにのみ送信され、保存されません。",
        "Password": "パスワード",
        "Sign in": "サインイン",
        "Sign in…": "サインイン…",
        "Change account…": "アカウントを変更…",
        "Status": "状態",
        "Connected": "接続済み",
        "Not signed in": "未サインイン",
        "Bluetooth pairing": "Bluetoothペアリング",
        "Current battery": "現在のバッテリー",
        "none": "なし",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "Bluetooth拒否 — 設定 → プライバシー → Bluetooth",
        "Searching… is the battery on and nearby?": "検索中… バッテリーの電源は入っていますか？",
        "✓ Current": "✓ 使用中",
        "Select": "選択",
        "Searching": "検索中",
        "Stop": "停止",
        "Change battery": "バッテリーを変更",
        "The daemon releases Bluetooth during the search": "検索中はデーモンがBluetoothを解放します",
        "Search…": "検索…",
        "Thresholds": "しきい値",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "使用可能範囲の実効%で判定。通常復帰は低電力しきい値より上に保たれます（ヒステリシス）。",
        "Notification": "通知",
        "Low power": "低電力モード",
        "Shutdown": "システム終了",
        "Return to normal": "通常モードへ復帰",
        "Options": "オプション",
        "Automatic low power": "自動低電力モード",
        "Throttles the Mac below the threshold, via pmset": "しきい値を下回るとpmsetでMacを制限します",
        "Low power as soon as on battery": "バッテリー駆動になったら即低電力",
        "Without waiting for the threshold, as soon as AC is lost": "しきい値を待たず、AC喪失と同時に",
        "Automatic shutdown": "自動システム終了",
        "Pseudo-hibernation at critical level": "残量危機時の疑似休止",
        "Only when the Mac is on the EcoFlow": "MacがEcoFlow接続時のみ",
        "Detected via AC output watts": "AC出力のワット数で検出",
        "Displayed % and time remaining are relative to the usable window.": "表示される%と残り時間は使用可能範囲に基づきます。",
        "Applied window": "適用中の範囲",
        "Charge limit": "充電上限",
        "80-85% daily extends LFP cell lifespan.": "日常は80〜85%にするとLFPセルが長持ちします。",
        "Manage the charge limit": "充電上限を管理",
        "Charge up to": "充電上限",
        "Discharge reserve": "放電リザーブ",
        "A reserve avoids deep discharge and keeps an emergency margin.": "リザーブは過放電を防ぎ、非常用の余裕を確保します。",
        "Manage the discharge limit": "放電下限を管理",
        "Minimum reserve": "最低リザーブ",
        "Measurement": "計測",
        "Refresh interval": "更新間隔",
        "\"Mac plugged\" threshold": "「Mac接続」しきい値",
        "Shutdown warning delay": "終了前の猶予",
        "Maintenance": "メンテナンス",
        "Configuration file": "設定ファイル",
        "Open": "開く",
        "Monitoring daemon": "監視デーモン",
        "Restart": "再起動",
        "Danger zone": "危険な操作",
        "Reset the app": "アプリをリセット",
        "Clears account and pairing, replays the full setup": "アカウントとペアリングを消去し、初期設定をやり直します",
        "Reset…": "リセット…",
        "Reset EcoFlowBar?": "EcoFlowBarをリセットしますか？",
        "Reset and relaunch": "リセットして再起動",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "EcoFlowアカウントとペアリングが消去され、アプリが初期設定を最初からやり直します。",
        "Hello.": "こんにちは。",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "あなたのEcoFlowを、メニューバーに。\n実残り時間、Macの自動保護、Bluetoothで100%ローカル。",
        "Get started": "はじめる",
        "Your account.": "アカウント。",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "EcoFlowのBluetoothには、バッテリーに紐づくアカウントIDが必要です。パスワードはEcoFlowにのみ送信され、保存されません。",
        "Account connected": "アカウント接続済み",
        "Continue": "続ける",
        "Later": "あとで",
        "In range.": "圏内。",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "Bluetoothアクセスが拒否されています — プライバシー設定でEcoFlowBarを許可してください。",
        "Open Privacy → Bluetooth": "プライバシー → Bluetoothを開く",
        "Turn on your battery and keep it nearby.": "バッテリーの電源を入れ、近くに置いてください。",
        "Choose the battery to monitor.": "監視するバッテリーを選択してください。",
        "Your rules.": "あなたのルール。",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "EcoFlowBarができること — すべて設定でいつでも変更できます。",
        "Notifications (source changes, low battery)": "通知（電源切替・残量低下）",
        "Automatic actions on the Mac (low power…)": "Macの自動アクション（低電力…）",
        "Limit the charge range (battery health)": "充電範囲を制限（バッテリー保護）",
        "Min reserve": "最低リザーブ",
        "Max charge": "充電上限",
        "The Mac's keys.": "Macの鍵。",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "低電力モード・正常終了・CPU計測のため、macOSが一度だけ管理者パスワードを求めます。任意 — 表示だけなら不要です。",
        "Permissions installed": "権限インストール済み",
        "Permissions not installed": "権限未インストール",
        "Install…": "インストール…",
        "Skip": "スキップ",
        "All set.": "準備完了。",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "インジケーターはメニューバーに常駐し、Bluetoothで更新されます。インターネット不要。調整はすべて設定から。",
        "Finish": "完了",
        "Back": "戻る",
        "Let's set up your EcoFlow battery.": "EcoFlowをセットアップしましょう。",
        "click to continue": "クリックして続行",
        "credentials rejected": "認証情報が拒否されました",
        "Unexpected server response": "サーバーから予期しない応答",
        "Network error": "ネットワークエラー",
    ]

    static let zh: [String: String] = [
        "state.charging": "充电中",
        "state.discharging": "电池供电",
        "state.plugged": "已接市电",
        "state.idle": "待机",
        "Settings": "设置",
        "Time remaining": "剩余时间",
        "Full charge in": "充满还需",
        "Mac on EcoFlow": "Mac接在EcoFlow上",
        "State": "状态",
        "Raw level": "实际电量",
        "window": "区间",
        "Power flow": "功率流",
        "Input": "输入",
        "AC output": "交流输出",
        "USB-C output": "USB-C输出",
        "Mac CPU (internal)": "Mac CPU（内部）",
        "Temperature": "温度",
        "Energy today": "今日电量",
        "Automatic actions on the Mac": "Mac自动操作",
        "Hibernate: save session and shut down": "休眠：保存会话并关机",
        "Daemon log": "守护进程日志",
        "Quit EcoFlowBar": "退出EcoFlowBar",
        "Save the session and shut down the Mac?": "保存会话并关闭Mac？",
        "Apps, tabs and tmux will be restored on next startup.": "应用、标签页和tmux将在下次启动时恢复。",
        "Cancel": "取消",
        "Shut down": "关机",
        "Cut the Mac's power?": "切断Mac的供电？",
        "Cut power": "切断",
        "Turn off AC output": "关闭交流输出",
        "Turn on AC output": "开启交流输出",
        "full in": "充满还需",
        "Daemon unreachable — see log": "守护进程无响应 — 查看日志",
        "Bluetooth search…": "蓝牙搜索中…",
        "EcoFlow out of range or off": "EcoFlow超出范围或已关机",
        "Not configured": "未配置",
        "Waiting for daemon…": "等待守护进程…",
        "History": "历史记录",
        "Collecting history…": "正在收集历史数据…",
        "Battery": "电池",
        "Load avg.": "平均功耗",
        "CPU avg.": "CPU平均",
        "EcoFlow Settings": "EcoFlow设置",
        "General": "通用",
        "Account": "账户",
        "Protection": "保护",
        "Advanced": "高级",
        "Behavior": "行为",
        "Master switch: low power, shutdown, alerts": "总开关：节能模式、关机、提醒",
        "Power source changes, low battery, temperature": "电源切换、低电量、温度",
        "Launch at login": "登录时启动",
        "Menu bar": "菜单栏",
        "Everything unchecked: the icon alone remains.": "全部取消勾选时，仅显示图标。",
        "Battery icon": "电池图标",
        "Percentage": "百分比",
        "Power draw": "功耗",
        "Language": "语言",
        "Automatic (system)": "自动（跟随系统）",
        "EcoFlow account": "EcoFlow账户",
        "Password sent only to EcoFlow, never stored.": "密码仅发送给EcoFlow，绝不保存。",
        "Password": "密码",
        "Sign in": "登录",
        "Sign in…": "登录…",
        "Change account…": "更换账户…",
        "Status": "状态",
        "Connected": "已登录",
        "Not signed in": "未登录",
        "Bluetooth pairing": "蓝牙配对",
        "Current battery": "当前电池",
        "none": "无",
        "Bluetooth denied — Settings → Privacy → Bluetooth": "蓝牙被拒绝 — 设置 → 隐私 → 蓝牙",
        "Searching… is the battery on and nearby?": "搜索中… 电池已开机且在附近吗？",
        "✓ Current": "✓ 当前",
        "Select": "选择",
        "Searching": "搜索中",
        "Stop": "停止",
        "Change battery": "更换电池",
        "The daemon releases Bluetooth during the search": "搜索期间守护进程会释放蓝牙",
        "Search…": "搜索…",
        "Thresholds": "阈值",
        "As effective % of the usable window. Return-to-normal stays above the low power threshold (hysteresis).": "以可用区间的有效百分比计算。恢复正常阈值保持在节能阈值之上（滞回）。",
        "Notification": "通知",
        "Low power": "节能模式",
        "Shutdown": "关机",
        "Return to normal": "恢复正常",
        "Options": "选项",
        "Automatic low power": "自动节能模式",
        "Throttles the Mac below the threshold, via pmset": "低于阈值时通过pmset限制Mac性能",
        "Low power as soon as on battery": "切换到电池后立即节能",
        "Without waiting for the threshold, as soon as AC is lost": "不等阈值，市电断开即生效",
        "Automatic shutdown": "自动关机",
        "Pseudo-hibernation at critical level": "电量危急时的伪休眠",
        "Only when the Mac is on the EcoFlow": "仅当Mac接在EcoFlow上时",
        "Detected via AC output watts": "通过交流输出瓦数检测",
        "Displayed % and time remaining are relative to the usable window.": "显示的百分比和剩余时间基于可用区间。",
        "Applied window": "当前区间",
        "Charge limit": "充电上限",
        "80-85% daily extends LFP cell lifespan.": "日常保持80-85%可延长磷酸铁锂电芯寿命。",
        "Manage the charge limit": "管理充电上限",
        "Charge up to": "充电至",
        "Discharge reserve": "放电保留",
        "A reserve avoids deep discharge and keeps an emergency margin.": "保留电量可避免过放并留出应急余量。",
        "Manage the discharge limit": "管理放电下限",
        "Minimum reserve": "最低保留",
        "Measurement": "测量",
        "Refresh interval": "刷新间隔",
        "\"Mac plugged\" threshold": "“Mac已接入”阈值",
        "Shutdown warning delay": "关机前警告时长",
        "Maintenance": "维护",
        "Configuration file": "配置文件",
        "Open": "打开",
        "Monitoring daemon": "监控守护进程",
        "Restart": "重启",
        "Danger zone": "危险操作",
        "Reset the app": "重置应用",
        "Clears account and pairing, replays the full setup": "清除账户和配对，重新进行完整设置",
        "Reset…": "重置…",
        "Reset EcoFlowBar?": "重置EcoFlowBar？",
        "Reset and relaunch": "重置并重启",
        "The EcoFlow account and pairing will be erased, then the app will relaunch the full setup.": "EcoFlow账户和配对将被清除，应用将重新开始完整设置。",
        "Hello.": "你好。",
        "Your EcoFlow battery, in the menu bar.\nReal time remaining, automatic Mac protection, 100% local over Bluetooth.": "你的EcoFlow电池，就在菜单栏。\n真实剩余时间、Mac自动保护，蓝牙连接100%本地运行。",
        "Get started": "开始",
        "Your account.": "你的账户。",
        "EcoFlow's Bluetooth requires the ID of the account linked to the battery. The password goes only to EcoFlow — never stored.": "EcoFlow蓝牙需要与电池绑定的账户ID。密码仅发送给EcoFlow，绝不保存。",
        "Account connected": "账户已连接",
        "Continue": "继续",
        "Later": "稍后",
        "In range.": "在范围内。",
        "Bluetooth access denied — allow EcoFlowBar in Privacy settings.": "蓝牙访问被拒绝 — 请在隐私设置中允许EcoFlowBar。",
        "Open Privacy → Bluetooth": "打开隐私 → 蓝牙",
        "Turn on your battery and keep it nearby.": "打开电池电源并放在附近。",
        "Choose the battery to monitor.": "选择要监控的电池。",
        "Your rules.": "你的规则。",
        "What EcoFlowBar may do for you — everything remains adjustable in Settings.": "EcoFlowBar能为你做什么 — 一切都可以在设置中随时调整。",
        "Notifications (source changes, low battery)": "通知（电源切换、低电量）",
        "Automatic actions on the Mac (low power…)": "Mac自动操作（节能…）",
        "Limit the charge range (battery health)": "限制充电区间（电池健康）",
        "Min reserve": "最低保留",
        "Max charge": "充电上限",
        "The Mac's keys.": "Mac的钥匙。",
        "To enable low power mode, clean shutdown and CPU measurement, macOS will ask once for your administrator password. Optional — display works without it.": "为启用节能模式、正常关机和CPU测量，macOS将询问一次管理员密码。可选 — 仅显示无需此权限。",
        "Permissions installed": "权限已安装",
        "Permissions not installed": "权限未安装",
        "Install…": "安装…",
        "Skip": "跳过",
        "All set.": "一切就绪。",
        "The indicator now lives in your menu bar, updated over Bluetooth, no Internet needed. All adjustments are in Settings.": "指示器现已常驻菜单栏，通过蓝牙更新，无需互联网。所有调整都在设置中。",
        "Finish": "完成",
        "Back": "返回",
        "Let's set up your EcoFlow battery.": "来设置你的EcoFlow电池吧。",
        "click to continue": "点击继续",
        "credentials rejected": "凭证被拒绝",
        "Unexpected server response": "服务器响应异常",
        "Network error": "网络错误",
    ]
}
